image: Visual Studio 2022

environment:
  JAVA_HOME: "C:\\Program Files\\Java\\jdk-11.0.28"
  PATH: "%JAVA_HOME%\\bin;%PATH%"

branches:
  only:
    - master

build: off

install:
  - start /B java -jar ./artifacts/app-order.jar
  - chmod +x gradlew

build_script:
  - .\gradlew.bat test --info
